# _config.yml

title: Python Programming
description: Python course labs and exercises
baseurl: "/Python-Programming"
remote_theme: pmarsceill/just-the-docs

just_the_docs:
  slicknav: true
  # Enable only the pages you list; do not auto-list everything
  browse_pages: false

  # Instruct Just the Docs to use _toc.yml for navigation
  toc:
    enabled: true

  show_edit_link: true
  stylesheets:
    - /Python-Programming/assets/css/custom.css

