title: Python Programming
description: Python course labs and exercises

remote_theme: pmarsceill/just-the-docs

repository: https://github.com/JSK-KML/Python-Programming

logo: /assets/images/logo.png

just_the_docs:
  slicknav: true
  navigation:
    collapse: true
  show_edit_link: true
  browse_pages: false


  stylesheets:
    - /assets/css/custom.css
