# _config.yml

title: Python Programming
description: Python course labs and exercises
baseurl: "/Python-Programming"
remote_theme: pmarsceill/just-the-docs

just_the_docs:
  slicknav: true

  # Use "nav:" for nested menus in the GitHub Pages / JTD version
  nav:
    collapse: true

  show_edit_link: true
  browse_pages: false

  stylesheets:
    - /Python-Programming/assets/css/custom.css
