name: Build & Deploy VitePress Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        # run npm ci in docs/ so it sees docs/package-lock.json
        run: npm ci --prefix docs

      - name: Build VitePress
        # run the build script (docs:build) in docs/
        run: npm run docs:build --prefix docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          # point at the built output under docs/.vitepress/dist
          folder: docs/.vitepress/dist
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
